### ISSUE TITLE
Other button/device uses

### ISSUE THREAD

**Issue by MJP-76** [haberda/tradfri_remotes#1]
Hi

Can you advise how I would use for devices other than lights

I have a light, fan and blinds I currently use with the ikea remote which has individual automations that listen to zigbee2mqtt and when detected fires of the action

example
Brighter button = Raise the blinds
Dimmer button = Lower blinds
Left arrow = Fan speed toggle down - high --> medium -- low
Right arrow = Fan speed toggle up - low --> medium --> high

Is this possible?

**Comment by haberda** [comment]
The way this code it written depends on the Home Assistant light services. Right now it does not support anything but lights. I might add other items in the future, but for now only lights are supported. Sorry, I know it says 'devices' in the readme.
